/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.viewers;

public abstract class PDFViewer_generated extends app.viewers.AbstractMapViewer implements star.event.EventController, star.event.Listener, star.hydrology.events.RenderableVisibleRaiser
{
	private static final long serialVersionUID = 1L;

	public  PDFViewer_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		super.eventRaised( event );
	}
	 
	public void raise_RenderableVisibleEvent()
	{
		(new star.hydrology.events.RenderableVisibleEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}