/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.viewers;

public abstract class SimpleIUHViewer_generated extends app.viewers.AbstractMapViewer implements star.event.EventController, star.event.Listener
{
	private static final long serialVersionUID = 1L;

	public  SimpleIUHViewer_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		super.eventRaised( event );
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}