/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.viewers;

public abstract class StreamOrderViewer_generated extends app.viewers.CustomAbstractMapViewer implements star.event.EventController, star.event.Listener, star.hydrology.events.ViewerChangeRaiser
{
	private static final long serialVersionUID = 1L;

	public  StreamOrderViewer_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydrology.events.StreamOrderStatisticsEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		super.eventRaised( event );
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.StreamOrderStatisticsEvent" ) && event.isValid() ) 
		{
			(new star.hydrology.events.ViewerChangeEvent(this,false)).raise();
		 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			setStreamOrderStatistics( (star.hydrology.events.StreamOrderStatisticsRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".setStreamOrderStatistics "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public void raise_ViewerChangeEvent()
	{
		(new star.hydrology.events.ViewerChangeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydrology.events.StreamOrderStatisticsEvent.class);
	}
	 
	abstract void setStreamOrderStatistics(star.hydrology.events.StreamOrderStatisticsRaiser r);
	 
}