/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package test;

public abstract class PropertiesTest_generated extends java.lang.Object implements star.event.EventController
{
	private star.event.Adapter adapter;
	private java.lang.String joe;
	private star.hydrology.data.formats.XYZ joe2 = null;
	private static final long serialVersionUID = 1L;

	public  PropertiesTest_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	protected java.lang.String getJoe()
	{
		return this.joe ;
	}
	 
	protected star.hydrology.data.formats.XYZ getJoe2()
	{
		return this.joe2 ;
	}
	 
	public void removeNotify()
	{
	}
	 
	protected void setJoe(java.lang.String joe)
	{
		this.joe = joe ;
	}
	 
	protected void setJoe2(star.hydrology.data.formats.XYZ joe2)
	{
		this.joe2 = joe2 ;
	}
	 
}