/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.worker.relief;

public abstract class HypsometricCurveWorker_generated extends java.lang.Object implements star.event.EventController, star.event.GatedListener, star.hydrology.events.HypsometricCurveRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  HypsometricCurveWorker_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		getAdapter().addGatedAnd( new Class[]{ star.hydrology.events.map.WatershedLayerEvent.class,star.hydrology.events.map.FlowaccumulationMapLayerEvent.class,star.hydrology.events.map.FlowdirectionMapLayerEvent.class},new Class[]{ star.hydrology.events.HypsometricCurveEvent.class},true);
	}
	 
	private void eventAndGateRaisedHandles(final star.event.Event in_event[], final boolean valid)
	{
		final star.event.Event[] event = in_event;
		if( event != null && valid && event.length == 3 && event[0].getClass().getName().equals( "star.hydrology.events.map.WatershedLayerEvent" ) && event[1].getClass().getName().equals( "star.hydrology.events.map.FlowaccumulationMapLayerEvent" ) && event[2].getClass().getName().equals( "star.hydrology.events.map.FlowdirectionMapLayerEvent" ) &&  true )
		{
			(new star.hydrology.events.HypsometricCurveEvent(this,false)).raise();
			utils.Runner.runOnThread(new Runnable() { 
				public void run() { 
					long start = System.nanoTime();
					handle( (star.hydrology.events.map.WatershedLayerRaiser)event[0].getSource(),(star.hydrology.events.map.FlowaccumulationMapLayerRaiser)event[1].getSource(),(star.hydrology.events.map.FlowdirectionMapLayerRaiser)event[2].getSource() );
					long end = System.nanoTime();
				if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handle "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public void eventsRaised(final star.event.Event event[], final boolean valid)
	{
		eventAndGateRaisedHandles(event,valid);
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handle(star.hydrology.events.map.WatershedLayerRaiser watershed, star.hydrology.events.map.FlowaccumulationMapLayerRaiser flowAcc, star.hydrology.events.map.FlowdirectionMapLayerRaiser flowDir);
	 
	public void raise_HypsometricCurveEvent()
	{
		(new star.hydrology.events.HypsometricCurveEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		getAdapter().removeGatedAnd( new Class[]{ star.hydrology.events.map.WatershedLayerEvent.class,star.hydrology.events.map.FlowaccumulationMapLayerEvent.class,star.hydrology.events.map.FlowdirectionMapLayerEvent.class},new Class[]{ star.hydrology.events.HypsometricCurveEvent.class});
	}
	 
}