/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.worker.relief;

public abstract class LinkConcentrationWorker_generated extends java.lang.Object implements star.event.EventController, star.event.GatedListener, star.event.Listener, star.hydrology.events.LinkConcentrationRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  LinkConcentrationWorker_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		getAdapter().addGatedAnd( new Class[]{ star.hydrology.events.map.WatershedLayerEvent.class,star.hydrology.events.map.FlowaccumulationMapLayerEvent.class,star.hydrology.events.map.FlowdirectionMapLayerEvent.class},new Class[]{ star.hydrology.events.LinkConcentrationEvent.class},true);
		getAdapter().addHandled(star.hydrology.events.GridStatisticsProviderChangeEvent.class);
	}
	 
	private void eventAndGateRaisedHandles(final star.event.Event in_event[], final boolean valid)
	{
		final star.event.Event[] event = in_event;
		if( !valid && event[0].getClass().getName().equals( "star.hydrology.events.map.WatershedLayerEvent" ) && event[1].getClass().getName().equals( "star.hydrology.events.map.FlowaccumulationMapLayerEvent" ) && event[2].getClass().getName().equals( "star.hydrology.events.map.FlowdirectionMapLayerEvent" ) &&  true )
		{
			(new star.hydrology.events.LinkConcentrationEvent(this,false)).raise();
			utils.Runner.runOnThread(new Runnable() { 
			 public void run() { 
			long start = System.nanoTime();handleInvalid( (star.hydrology.events.map.WatershedLayerRaiser)event[0].getSource(),(star.hydrology.events.map.FlowaccumulationMapLayerRaiser)event[1].getSource(),(star.hydrology.events.map.FlowdirectionMapLayerRaiser)event[2].getSource() );
			long end = System.nanoTime();
				if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleInvalid "  + ( end-start )/1000000 ); } }},this,2);
		}
		if( event != null && valid && event.length == 3 && event[0].getClass().getName().equals( "star.hydrology.events.map.WatershedLayerEvent" ) && event[1].getClass().getName().equals( "star.hydrology.events.map.FlowaccumulationMapLayerEvent" ) && event[2].getClass().getName().equals( "star.hydrology.events.map.FlowdirectionMapLayerEvent" ) &&  true )
		{
			(new star.hydrology.events.LinkConcentrationEvent(this,false)).raise();
			utils.Runner.runOnThread(new Runnable() { 
				public void run() { 
					long start = System.nanoTime();
					handle( (star.hydrology.events.map.WatershedLayerRaiser)event[0].getSource(),(star.hydrology.events.map.FlowaccumulationMapLayerRaiser)event[1].getSource(),(star.hydrology.events.map.FlowdirectionMapLayerRaiser)event[2].getSource() );
					long end = System.nanoTime();
				if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handle "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.GridStatisticsProviderChangeEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			setAdjustableValue( (star.hydrology.events.GridStatisticsProviderChangeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".setAdjustableValue "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public void eventsRaised(final star.event.Event event[], final boolean valid)
	{
		eventAndGateRaisedHandles(event,valid);
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handle(star.hydrology.events.map.WatershedLayerRaiser watershed, star.hydrology.events.map.FlowaccumulationMapLayerRaiser flowAcc, star.hydrology.events.map.FlowdirectionMapLayerRaiser flowDir);
	 
	abstract void handleInvalid(star.hydrology.events.map.WatershedLayerRaiser watershed, star.hydrology.events.map.FlowaccumulationMapLayerRaiser flowAcc, star.hydrology.events.map.FlowdirectionMapLayerRaiser flowDir);
	 
	public void raise_LinkConcentrationEvent()
	{
		(new star.hydrology.events.LinkConcentrationEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		getAdapter().removeGatedAnd( new Class[]{ star.hydrology.events.map.WatershedLayerEvent.class,star.hydrology.events.map.FlowaccumulationMapLayerEvent.class,star.hydrology.events.map.FlowdirectionMapLayerEvent.class},new Class[]{ star.hydrology.events.LinkConcentrationEvent.class});
		getAdapter().removeHandled(star.hydrology.events.GridStatisticsProviderChangeEvent.class);
	}
	 
	abstract void setAdjustableValue(star.hydrology.events.GridStatisticsProviderChangeRaiser r);
	 
}