/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.worker.relief;

public abstract class SlopeAreaWorker_generated extends java.lang.Object implements star.event.EventController, star.event.GatedListener, star.hydrology.events.SlopeAreaRaiser
{
	private star.event.Adapter adapter;
	private star.hydro.rainfall.TimeSeries dataset;
	private star.hydrology.events.interfaces.PaletteRenderableLayer flowAcc;
	private java.awt.Point origin;
	private static final long serialVersionUID = 1L;
	private star.hydrology.events.interfaces.PaletteRenderableLayer slope;
	private star.hydrology.events.interfaces.PaletteRenderableLayer watershed;

	public  SlopeAreaWorker_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		getAdapter().addGatedAnd( new Class[]{ star.hydrology.events.map.WatershedLayerEvent.class,star.hydrology.events.map.SlopePDFMapLayerEvent.class,star.hydrology.events.map.FlowaccumulationMapLayerEvent.class},new Class[]{ star.hydrology.events.SlopeAreaEvent.class},true);
	}
	 
	abstract void calculateSlopeArea(star.hydrology.events.map.WatershedLayerRaiser watershed, star.hydrology.events.map.SlopePDFMapLayerRaiser slope, star.hydrology.events.map.FlowaccumulationMapLayerRaiser flowAcc);
	 
	private void eventAndGateRaisedHandles(final star.event.Event in_event[], final boolean valid)
	{
		final star.event.Event[] event = in_event;
		if( event != null && valid && event.length == 3 && event[0].getClass().getName().equals( "star.hydrology.events.map.WatershedLayerEvent" ) && event[1].getClass().getName().equals( "star.hydrology.events.map.SlopePDFMapLayerEvent" ) && event[2].getClass().getName().equals( "star.hydrology.events.map.FlowaccumulationMapLayerEvent" ) &&  true )
		{
			(new star.hydrology.events.SlopeAreaEvent(this,false)).raise();
			utils.Runner.runOnThread(new Runnable() { 
				public void run() { 
					long start = System.nanoTime();
					calculateSlopeArea( (star.hydrology.events.map.WatershedLayerRaiser)event[0].getSource(),(star.hydrology.events.map.SlopePDFMapLayerRaiser)event[1].getSource(),(star.hydrology.events.map.FlowaccumulationMapLayerRaiser)event[2].getSource() );
					long end = System.nanoTime();
				if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".calculateSlopeArea "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public void eventsRaised(final star.event.Event event[], final boolean valid)
	{
		eventAndGateRaisedHandles(event,valid);
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public star.hydro.rainfall.TimeSeries getDataset()
	{
		return this.dataset ;
	}
	 
	protected star.hydrology.events.interfaces.PaletteRenderableLayer getFlowAcc()
	{
		return this.flowAcc ;
	}
	 
	protected java.awt.Point getOrigin()
	{
		return this.origin ;
	}
	 
	protected star.hydrology.events.interfaces.PaletteRenderableLayer getSlope()
	{
		return this.slope ;
	}
	 
	protected star.hydrology.events.interfaces.PaletteRenderableLayer getWatershed()
	{
		return this.watershed ;
	}
	 
	public void raise_SlopeAreaEvent()
	{
		(new star.hydrology.events.SlopeAreaEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		getAdapter().removeGatedAnd( new Class[]{ star.hydrology.events.map.WatershedLayerEvent.class,star.hydrology.events.map.SlopePDFMapLayerEvent.class,star.hydrology.events.map.FlowaccumulationMapLayerEvent.class},new Class[]{ star.hydrology.events.SlopeAreaEvent.class});
	}
	 
	protected void setDataset(star.hydro.rainfall.TimeSeries dataset)
	{
		this.dataset = dataset ;
	}
	 
	protected void setFlowAcc(star.hydrology.events.interfaces.PaletteRenderableLayer flowAcc)
	{
		this.flowAcc = flowAcc ;
	}
	 
	protected void setOrigin(java.awt.Point origin)
	{
		this.origin = origin ;
	}
	 
	protected void setSlope(star.hydrology.events.interfaces.PaletteRenderableLayer slope)
	{
		this.slope = slope ;
	}
	 
	protected void setWatershed(star.hydrology.events.interfaces.PaletteRenderableLayer watershed)
	{
		this.watershed = watershed ;
	}
	 
}