/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app;

public abstract class AccumulationThresholdSlider_generated extends javax.swing.JSlider implements star.event.EventController, starhydro.events.AccumulationThresholdChangedRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_AccumulationThresholdChangedEvent()
	{
		(new starhydro.events.AccumulationThresholdChangedEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}