/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app;

public abstract class ScaleSlider_generated extends javax.swing.JSlider implements star.event.EventController, star.event.Listener, starhydro.events.ViewScaleChangedRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  ScaleSlider_generated()
	{
		super();
	}
	 
	public  ScaleSlider_generated(int int0, int int1, int int2, int int3)
	{
		super( int0,int1,int2,int3);
	}
	 
	public  ScaleSlider_generated(int int0, int int1, int int2)
	{
		super( int0,int1,int2);
	}
	 
	public  ScaleSlider_generated(int int0, int int1)
	{
		super( int0,int1);
	}
	 
	public  ScaleSlider_generated(int int0)
	{
		super( int0);
	}
	 
	public  ScaleSlider_generated(javax.swing.BoundedRangeModel boundedRangeModel)
	{
		super( boundedRangeModel);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(starhydro.events.ViewScaleChangedEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "starhydro.events.ViewScaleChangedEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleScaleChange( (starhydro.events.ViewScaleChangedRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleScaleChange "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handleScaleChange(starhydro.events.ViewScaleChangedRaiser r);
	 
	public void raise_ViewScaleChangedEvent()
	{
		(new starhydro.events.ViewScaleChangedEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(starhydro.events.ViewScaleChangedEvent.class);
	}
	 
}