/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydro.filemanager.common;

public abstract class ProcessedMapProject_generated extends java.lang.Object implements star.event.EventController, star.swing.events.ProgressRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  ProcessedMapProject_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_ProgressEvent()
	{
		(new star.swing.events.ProgressEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
	}
	 
}