/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.ui.selectors;

public abstract class ComboBoxSelector_generated extends mit.swing.xJPanel implements star.event.EventController, star.event.Listener
{
	private static final long serialVersionUID = 1L;

	public  ComboBoxSelector_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(mit.awt.event.ItemEvent.class );
		getAdapter().addContained(mit.awt.event.ActionEvent.class );
		getAdapter().addContained(mit.awt.event.ItemEvent.class );
		getAdapter().addExcludeExternal(mit.awt.event.ActionEvent.class );
		getAdapter().addExcludeExternal(mit.awt.event.ItemEvent.class );
		getAdapter().addHandled(star.hydrology.events.InitializeEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedEventHandle(event);
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedEventHandle(star.event.Event event)
	{
		if( event.getClass().getName().equals( "mit.awt.event.ItemEvent" ) ) { 
			mit.awt.event.ItemRaiser r = (mit.awt.event.ItemRaiser)event.getSource();
			if(event.isValid())
			{
				handleEvent( r );
			}
			else
			{
				handleInvalidEvent( r );
			}
		}
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.InitializeEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleEvent( (star.hydrology.events.InitializeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleEvent "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	abstract void handleEvent(mit.awt.event.ItemRaiser raiser);
	 
	abstract void handleEvent(star.hydrology.events.InitializeRaiser raiser);
	 
	void handleInvalidEvent(mit.awt.event.ItemRaiser raiser)
	{
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(mit.awt.event.ItemEvent.class );
		getAdapter().removeContained(mit.awt.event.ActionEvent.class );
		getAdapter().removeContained(mit.awt.event.ItemEvent.class );
		getAdapter().removeExcludeExternal(mit.awt.event.ActionEvent.class );
		getAdapter().removeExcludeExternal(mit.awt.event.ItemEvent.class );
		getAdapter().removeHandled(star.hydrology.events.InitializeEvent.class);
	}
	 
}