/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.model;

public abstract class FloatWorld_generated extends java.lang.Object implements star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  FloatWorld_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void removeNotify()
	{
	}
	 
}