/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.worker;

public abstract class StreamNetworkWorker_generated extends app.worker.AbstractWorker implements star.event.EventController, star.event.GatedListener, star.event.Listener, star.hydrology.events.StreamRootChangeRaiser
{
	private javax.vecmath.Point3f center;
	private app.worker.streamnetwork.Channel channelRoot;
	private star.hydrology.events.interfaces.PaletteRenderableLayer flowAccomulation;
	private star.hydrology.events.interfaces.PaletteRenderableLayer flowDirection;
	private static final long serialVersionUID = 1L;
	private app.worker.streamnetwork.Stream streamRoot;
	private star.hydrology.events.interfaces.PaletteRenderableLayer terrain;
	private java.awt.Point watershedOrigin;

	public  StreamNetworkWorker_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydrology.events.GridStatisticsProviderChangeEvent.class);
		getAdapter().addHandled(star.hydrology.events.SelectWatershedOriginEvent.class);
		getAdapter().addGatedAnd( new Class[]{ star.hydrology.events.map.FilledMapLayerEvent.class,star.hydrology.events.map.FlowaccumulationMapLayerEvent.class,star.hydrology.events.map.FlowdirectionMapLayerEvent.class},new Class[]{ star.hydrology.events.StreamRootChangeEvent.class},true);
	}
	 
	private void eventAndGateRaisedHandles(final star.event.Event in_event[], final boolean valid)
	{
		final star.event.Event[] event = in_event;
		if( event != null && valid && event.length == 3 && event[0].getClass().getName().equals( "star.hydrology.events.map.FilledMapLayerEvent" ) && event[1].getClass().getName().equals( "star.hydrology.events.map.FlowaccumulationMapLayerEvent" ) && event[2].getClass().getName().equals( "star.hydrology.events.map.FlowdirectionMapLayerEvent" ) &&  true )
		{
			(new star.hydrology.events.StreamRootChangeEvent(this,false)).raise();
			utils.Runner.runOnThread(new Runnable() { 
				public void run() { 
					long start = System.nanoTime();
					setTerrain( (star.hydrology.events.map.FilledMapLayerRaiser)event[0].getSource(),(star.hydrology.events.map.FlowaccumulationMapLayerRaiser)event[1].getSource(),(star.hydrology.events.map.FlowdirectionMapLayerRaiser)event[2].getSource() );
					long end = System.nanoTime();
				if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".setTerrain "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		super.eventRaised( event );
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.GridStatisticsProviderChangeEvent" ) && event.isValid() ) 
		{
			(new star.hydrology.events.StreamRootChangeEvent(this,false)).raise();
		 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			setAccumulationTreshold( (star.hydrology.events.GridStatisticsProviderChangeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".setAccumulationTreshold "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.SelectWatershedOriginEvent" ) && event.isValid() ) 
		{
			(new star.hydrology.events.StreamRootChangeEvent(this,false)).raise();
		 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			setWatershedOrigin( (star.hydrology.events.SelectWatershedOriginRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".setWatershedOrigin "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public void eventsRaised(final star.event.Event event[], final boolean valid)
	{
		eventAndGateRaisedHandles(event,valid);
	}
	 
	protected javax.vecmath.Point3f getCenter()
	{
		return this.center ;
	}
	 
	protected app.worker.streamnetwork.Channel getChannelRoot()
	{
		return this.channelRoot ;
	}
	 
	protected star.hydrology.events.interfaces.PaletteRenderableLayer getFlowAccomulation()
	{
		return this.flowAccomulation ;
	}
	 
	protected star.hydrology.events.interfaces.PaletteRenderableLayer getFlowDirection()
	{
		return this.flowDirection ;
	}
	 
	public app.worker.streamnetwork.Stream getStreamRoot()
	{
		return this.streamRoot ;
	}
	 
	protected star.hydrology.events.interfaces.PaletteRenderableLayer getTerrain()
	{
		return this.terrain ;
	}
	 
	protected java.awt.Point getWatershedOrigin()
	{
		return this.watershedOrigin ;
	}
	 
	public void raise_StreamRootChangeEvent()
	{
		(new star.hydrology.events.StreamRootChangeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydrology.events.GridStatisticsProviderChangeEvent.class);
		getAdapter().removeHandled(star.hydrology.events.SelectWatershedOriginEvent.class);
		getAdapter().removeGatedAnd( new Class[]{ star.hydrology.events.map.FilledMapLayerEvent.class,star.hydrology.events.map.FlowaccumulationMapLayerEvent.class,star.hydrology.events.map.FlowdirectionMapLayerEvent.class},new Class[]{ star.hydrology.events.StreamRootChangeEvent.class});
	}
	 
	abstract void setAccumulationTreshold(star.hydrology.events.GridStatisticsProviderChangeRaiser r);
	 
	protected void setCenter(javax.vecmath.Point3f center)
	{
		this.center = center ;
	}
	 
	protected void setChannelRoot(app.worker.streamnetwork.Channel channelRoot)
	{
		this.channelRoot = channelRoot ;
	}
	 
	protected void setFlowAccomulation(star.hydrology.events.interfaces.PaletteRenderableLayer flowAccomulation)
	{
		this.flowAccomulation = flowAccomulation ;
	}
	 
	protected void setFlowDirection(star.hydrology.events.interfaces.PaletteRenderableLayer flowDirection)
	{
		this.flowDirection = flowDirection ;
	}
	 
	protected void setStreamRoot(app.worker.streamnetwork.Stream streamRoot)
	{
		this.streamRoot = streamRoot ;
	}
	 
	protected void setTerrain(star.hydrology.events.interfaces.PaletteRenderableLayer terrain)
	{
		this.terrain = terrain ;
	}
	 
	abstract void setTerrain(star.hydrology.events.map.FilledMapLayerRaiser terrain, star.hydrology.events.map.FlowaccumulationMapLayerRaiser flowAcc, star.hydrology.events.map.FlowdirectionMapLayerRaiser flowDir);
	 
	protected void setWatershedOrigin(java.awt.Point watershedOrigin)
	{
		this.watershedOrigin = watershedOrigin ;
	}
	 
	abstract void setWatershedOrigin(star.hydrology.events.SelectWatershedOriginRaiser r);
	 
}