/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.worker.map;

public abstract class FlowUpstramDirectionWorker_generated extends java.lang.Object implements star.event.EventController, star.event.Listener, star.hydrology.events.map.FlowUpstreamDirectionRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  FlowUpstramDirectionWorker_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		getAdapter().addHandled(star.hydrology.events.map.FlowdirectionMapLayerEvent.class);
	}
	 
	abstract void calculate(star.hydrology.events.map.FlowdirectionMapLayerRaiser flowDirectionRaiser);
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.map.FlowdirectionMapLayerEvent" ) && !event.isValid() ) 
		{
			(new star.hydrology.events.map.FlowUpstreamDirectionEvent(this,false)).raise();
		 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			stop( (star.hydrology.events.map.FlowdirectionMapLayerRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".stop "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.map.FlowdirectionMapLayerEvent" ) && event.isValid() ) 
		{
			(new star.hydrology.events.map.FlowUpstreamDirectionEvent(this,false)).raise();
		 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			calculate( (star.hydrology.events.map.FlowdirectionMapLayerRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".calculate "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_FlowUpstreamDirectionEvent()
	{
		(new star.hydrology.events.map.FlowUpstreamDirectionEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		getAdapter().removeHandled(star.hydrology.events.map.FlowdirectionMapLayerEvent.class);
	}
	 
	abstract void stop(star.hydrology.events.map.FlowdirectionMapLayerRaiser flowDirectionRaiser);
	 
}