/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.worker.map;

public abstract class ProjectionWorker_generated extends app.worker.AbstractWorker implements star.event.EventController, star.event.Listener, star.hydrology.events.map.TerrainMapLayerRaiser
{
	private static final long serialVersionUID = 1L;

	public  ProjectionWorker_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydrology.events.UnprojectedMapChangedEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		super.eventRaised( event );
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.UnprojectedMapChangedEvent" ) && event.isValid() ) 
		{
			(new star.hydrology.events.map.TerrainMapLayerEvent(this,false)).raise();
		 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleEvent( (star.hydrology.events.UnprojectedMapChangedRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleEvent "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.UnprojectedMapChangedEvent" ) && !event.isValid() ) 
		{
			(new star.hydrology.events.map.TerrainMapLayerEvent(this,false)).raise();
		 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleInvalidEvent( (star.hydrology.events.UnprojectedMapChangedRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleInvalidEvent "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	abstract void handleEvent(star.hydrology.events.UnprojectedMapChangedRaiser raiser1);
	 
	abstract void handleInvalidEvent(star.hydrology.events.UnprojectedMapChangedRaiser raiser1);
	 
	public void raise_TerrainMapLayerEvent()
	{
		(new star.hydrology.events.map.TerrainMapLayerEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydrology.events.UnprojectedMapChangedEvent.class);
	}
	 
}