/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.layers;

public abstract class TableModel_generated extends javax.swing.table.AbstractTableModel implements star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  TableModel_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void removeNotify()
	{
	}
	 
}