/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.viewers.map;

public abstract class RegionalizationForm_generated extends javax.swing.JPanel implements star.event.EventController, star.event.Listener, star.hydrology.events.map.RegionalizationRaiser
{
	private star.event.Adapter adapter;
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  RegionalizationForm_generated()
	{
		super();
	}
	 
	public  RegionalizationForm_generated(boolean boolean0)
	{
		super( boolean0);
	}
	 
	public  RegionalizationForm_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super( layoutManager,boolean0);
	}
	 
	public  RegionalizationForm_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addContained(java.awt.event.ActionEvent.class );
		getAdapter().addContained(mit.swing.event.ChangeEvent.class );
		getAdapter().addExcludeExternal(java.awt.event.ActionEvent.class );
		getAdapter().addExcludeExternal(mit.swing.event.ChangeEvent.class );
		getAdapter().addHandled(star.hydrology.events.map.RegionalizationStatisticsEvent.class);
		getAdapter().addHandled(mit.awt.event.ActionEvent.class);
		getAdapter().addHandled(star.hydrology.events.map.FilledMapLayerEvent.class);
	}
	 
	abstract void buttons(mit.awt.event.ActionRaiser event);
	 
	abstract void cellSize(star.hydrology.events.map.FilledMapLayerRaiser map);
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.map.RegionalizationStatisticsEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			updateStatistics( (star.hydrology.events.map.RegionalizationStatisticsRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".updateStatistics "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "mit.awt.event.ActionEvent" ) && event.isValid() ) 
		{
			(new star.hydrology.events.map.RegionalizationEvent(this,false)).raise();
		 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			buttons( (mit.awt.event.ActionRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".buttons "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.map.FilledMapLayerEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			cellSize( (star.hydrology.events.map.FilledMapLayerRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".cellSize "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("app.viewers.map.RegionalizationForm");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	public void raise_RegionalizationEvent()
	{
		(new star.hydrology.events.map.RegionalizationEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeContained(java.awt.event.ActionEvent.class );
		getAdapter().removeContained(mit.swing.event.ChangeEvent.class );
		getAdapter().removeExcludeExternal(java.awt.event.ActionEvent.class );
		getAdapter().removeExcludeExternal(mit.swing.event.ChangeEvent.class );
		getAdapter().removeHandled(star.hydrology.events.map.RegionalizationStatisticsEvent.class);
		getAdapter().removeHandled(mit.awt.event.ActionEvent.class);
		getAdapter().removeHandled(star.hydrology.events.map.FilledMapLayerEvent.class);
	}
	 
	abstract void updateStatistics(star.hydrology.events.map.RegionalizationStatisticsRaiser r);
	 
}