/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydro.rainfall;

public abstract class ConvoluteChart_generated extends star.hydrology.ui.chart.AbstractChart implements star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  ConvoluteChart_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydro.rainfall.ConvolutionChartBinsEvent.class);
		getAdapter().addHandled(star.hydro.rainfall.ConvolutedTimeSeriesEvent.class);
		getAdapter().addHandled(star.hydro.rainfall.ConvolutionPaletteEvent.class);
	}
	 
	abstract void convolutionPalette(star.hydro.rainfall.ConvolutionPaletteRaiser r);
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydro.rainfall.ConvolutionChartBinsEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleRainfall( (star.hydro.rainfall.ConvolutionChartBinsRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleRainfall "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydro.rainfall.ConvolutedTimeSeriesEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleRainfall( (star.hydro.rainfall.ConvolutedTimeSeriesRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleRainfall "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydro.rainfall.ConvolutionPaletteEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			convolutionPalette( (star.hydro.rainfall.ConvolutionPaletteRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".convolutionPalette "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handleRainfall(star.hydro.rainfall.ConvolutedTimeSeriesRaiser r);
	 
	abstract void handleRainfall(star.hydro.rainfall.ConvolutionChartBinsRaiser r);
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydro.rainfall.ConvolutionChartBinsEvent.class);
		getAdapter().removeHandled(star.hydro.rainfall.ConvolutedTimeSeriesEvent.class);
		getAdapter().removeHandled(star.hydro.rainfall.ConvolutionPaletteEvent.class);
	}
	 
}