/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydro.rainfall;

public class ConvolutionPaletteEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ConvolutionPaletteEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ConvolutionPaletteEvent(star.hydro.rainfall.ConvolutionPaletteEvent event)
	{
		super( event ) ;
	}
	 
	public  ConvolutionPaletteEvent(star.hydro.rainfall.ConvolutionPaletteRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}