/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydro.rainfall;

public abstract class RainfallGauges_generated extends javax.swing.JPanel implements star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  RainfallGauges_generated()
	{
		super();
	}
	 
	public  RainfallGauges_generated(boolean boolean0)
	{
		super( boolean0);
	}
	 
	public  RainfallGauges_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super( layoutManager,boolean0);
	}
	 
	public  RainfallGauges_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydrology.events.RainfallGaugesEvent.class);
		getAdapter().addHandled(star.hydrology.events.map.FilledMapLayerEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.RainfallGaugesEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			updateGauges( (star.hydrology.events.RainfallGaugesRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".updateGauges "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.map.FilledMapLayerEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			updateTerrain( (star.hydrology.events.map.FilledMapLayerRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".updateTerrain "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydrology.events.RainfallGaugesEvent.class);
		getAdapter().removeHandled(star.hydrology.events.map.FilledMapLayerEvent.class);
	}
	 
	abstract void updateGauges(star.hydrology.events.RainfallGaugesRaiser raiser);
	 
	abstract void updateTerrain(star.hydrology.events.map.FilledMapLayerRaiser raiser);
	 
}