/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydro.rainfall;

public abstract class RainfallPanel_generated extends javax.swing.JTabbedPane implements star.event.EventController, star.hydrology.events.RainfallGaugesTimeseriesRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  RainfallPanel_generated()
	{
		super();
	}
	 
	public  RainfallPanel_generated(int int0, int int1)
	{
		super( int0,int1);
	}
	 
	public  RainfallPanel_generated(int int0)
	{
		super( int0);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_RainfallGaugesTimeseriesEvent()
	{
		(new star.hydrology.events.RainfallGaugesTimeseriesEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}