/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydro.rainfall;

public abstract class TimeSeries_generated extends java.lang.Object implements star.event.EventController, star.hydro.rainfall.TimeSeriesRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  TimeSeries_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_TimeSeriesEvent()
	{
		(new star.hydro.rainfall.TimeSeriesEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
	}
	 
}