/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydro.rainfall;

public class TimeSeriesEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  TimeSeriesEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  TimeSeriesEvent(star.hydro.rainfall.TimeSeriesEvent event)
	{
		super( event ) ;
	}
	 
	public  TimeSeriesEvent(star.hydro.rainfall.TimeSeriesRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}