/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app;

public abstract class HydrologyViewer2D_generated extends javax.swing.JComponent implements star.event.EventController, star.event.Listener, star.hydrology.events.Select3DRaiser
{
	private star.event.Adapter adapter;
	private java.awt.Dimension preferredScrollableViewportSize = new java.awt.Dimension(800,600);
	private java.awt.Dimension preferredSize = new java.awt.Dimension(800,600);
	private float scale = 1;
	private boolean scrollableTracksViewportHeight = false;
	private boolean scrollableTracksViewportWidth = false;
	private static final long serialVersionUID = 1L;

	public  HydrologyViewer2D_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydrology.events.map.FilledMapLayerEvent.class);
		getAdapter().addHandled(star.hydrology.events.GridStatisticsProviderChangeEvent.class);
		getAdapter().addHandled(star.hydrology.events.PaletteChangedEvent.class);
		getAdapter().addHandled(star.hydrology.events.StreamOrderStatisticsEvent.class);
		getAdapter().addHandled(star.hydrology.events.LayerChangedEvent.class);
		getAdapter().addHandled(star.hydrology.events.VisibilityChangedEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.map.FilledMapLayerEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			updateTerrain( (star.hydrology.events.map.FilledMapLayerRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".updateTerrain "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.GridStatisticsProviderChangeEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			setThreshold( (star.hydrology.events.GridStatisticsProviderChangeRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".setThreshold "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.PaletteChangedEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			updatePalette( (star.hydrology.events.PaletteChangedRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".updatePalette "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.StreamOrderStatisticsEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			setStreamOrderStatistics( (star.hydrology.events.StreamOrderStatisticsRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".setStreamOrderStatistics "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.LayerChangedEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			updateLayers( (star.hydrology.events.LayerChangedRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".updateLayers "  + ( end-start )/1000000 ); } }},this,2);
		}if( event.getClass().getName().equals( "star.hydrology.events.VisibilityChangedEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			updateVisibility( (star.hydrology.events.VisibilityChangedRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".updateVisibility "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public java.awt.Dimension getPreferredScrollableViewportSize()
	{
		return this.preferredScrollableViewportSize ;
	}
	 
	public java.awt.Dimension getPreferredSize()
	{
		return this.preferredSize ;
	}
	 
	protected float getScale()
	{
		return this.scale ;
	}
	 
	public boolean getScrollableTracksViewportHeight()
	{
		return this.scrollableTracksViewportHeight ;
	}
	 
	public boolean getScrollableTracksViewportWidth()
	{
		return this.scrollableTracksViewportWidth ;
	}
	 
	public boolean isScrollableTracksViewportHeight()
	{
		return this.scrollableTracksViewportHeight ;
	}
	 
	public boolean isScrollableTracksViewportWidth()
	{
		return this.scrollableTracksViewportWidth ;
	}
	 
	public void raise_Select3DEvent()
	{
		(new star.hydrology.events.Select3DEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydrology.events.map.FilledMapLayerEvent.class);
		getAdapter().removeHandled(star.hydrology.events.GridStatisticsProviderChangeEvent.class);
		getAdapter().removeHandled(star.hydrology.events.PaletteChangedEvent.class);
		getAdapter().removeHandled(star.hydrology.events.StreamOrderStatisticsEvent.class);
		getAdapter().removeHandled(star.hydrology.events.LayerChangedEvent.class);
		getAdapter().removeHandled(star.hydrology.events.VisibilityChangedEvent.class);
	}
	 
	protected void setPreferredScrollableViewportSize(java.awt.Dimension preferredScrollableViewportSize)
	{
		this.preferredScrollableViewportSize = preferredScrollableViewportSize ;
	}
	 
	public void setPreferredSize(java.awt.Dimension preferredSize)
	{
		this.preferredSize = preferredSize ;
	}
	 
	protected void setScale(float scale)
	{
		this.scale = scale ;
	}
	 
	protected void setScrollableTracksViewportHeight(boolean scrollableTracksViewportHeight)
	{
		this.scrollableTracksViewportHeight = scrollableTracksViewportHeight ;
	}
	 
	protected void setScrollableTracksViewportWidth(boolean scrollableTracksViewportWidth)
	{
		this.scrollableTracksViewportWidth = scrollableTracksViewportWidth ;
	}
	 
	abstract void setStreamOrderStatistics(star.hydrology.events.StreamOrderStatisticsRaiser r);
	 
	abstract void setThreshold(star.hydrology.events.GridStatisticsProviderChangeRaiser r);
	 
	abstract void updateLayers(star.hydrology.events.LayerChangedRaiser raiser);
	 
	abstract void updatePalette(star.hydrology.events.PaletteChangedRaiser raiser);
	 
	abstract void updateTerrain(star.hydrology.events.map.FilledMapLayerRaiser raiser);
	 
	abstract void updateVisibility(star.hydrology.events.VisibilityChangedRaiser raiser);
	 
}