/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app;

public abstract class HydrologyViewer_generated extends java.awt.Panel implements star.event.EventController, star.event.Listener, star.events.common.InitializeRaiser
{
	private star.event.Adapter adapter;
	private app.HydrologyContainer hydrologyContainer;
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  HydrologyViewer_generated()
	{
		super();
	}
	 
	public  HydrologyViewer_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydrology.events.RenderableVisibleEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.RenderableVisibleEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			updateBranchGroup( (star.hydrology.events.RenderableVisibleRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".updateBranchGroup "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	protected app.HydrologyContainer getHydrologyContainer()
	{
		return this.hydrologyContainer ;
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("app.HydrologyViewer");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	public void raise_InitializeEvent()
	{
		(new star.events.common.InitializeEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydrology.events.RenderableVisibleEvent.class);
	}
	 
	protected void setHydrologyContainer(app.HydrologyContainer hydrologyContainer)
	{
		this.hydrologyContainer = hydrologyContainer ;
	}
	 
	abstract void updateBranchGroup(star.hydrology.events.RenderableVisibleRaiser r);
	 
}