/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app;

public abstract class Main_generated extends java.awt.Frame implements star.event.EventController
{
	private star.event.Adapter adapter;
	private java.util.prefs.Preferences preferences = null;
	private static final long serialVersionUID = 1L;

	public  Main_generated() throws java.awt.HeadlessException
	{
		super();
	}
	 
	public  Main_generated(java.awt.GraphicsConfiguration graphicsConfiguration)
	{
		super( graphicsConfiguration);
	}
	 
	public  Main_generated(java.lang.String string, java.awt.GraphicsConfiguration graphicsConfiguration)
	{
		super( string,graphicsConfiguration);
	}
	 
	public  Main_generated(java.lang.String string) throws java.awt.HeadlessException
	{
		super( string);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch( plugin.PluginException ex )
		{
			ex.printStackTrace();
		}
		return preferences;
	}
	 
	public java.util.prefs.Preferences getPreferences()
	{
		if( preferences == null )
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("app.Main");
			}
			catch( plugin.PluginException ex )
			{
				ex.printStackTrace();
			}
		}
		return preferences;
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}