/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.giuh;

public class GIUHVelocitiesEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  GIUHVelocitiesEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  GIUHVelocitiesEvent(star.hydrology.events.giuh.GIUHVelocitiesEvent event)
	{
		super( event ) ;
	}
	 
	public  GIUHVelocitiesEvent(star.hydrology.events.giuh.GIUHVelocitiesRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}