/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.algorithms;

public abstract class BackgroundProcess_generated extends java.lang.Object implements star.event.EventController, starhydro.events.BackgroundProcessRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  BackgroundProcess_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_BackgroundProcessEvent()
	{
		(new starhydro.events.BackgroundProcessEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
	}
	 
}