/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.ui.chart.horton;

public abstract class LogScale_generated extends javax.swing.JCheckBox implements star.event.EventController, star.hydrology.ui.chart.horton.LogScaleRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  LogScale_generated()
	{
		super();
	}
	 
	public  LogScale_generated(java.lang.String string, boolean boolean0)
	{
		super( string,boolean0);
	}
	 
	public  LogScale_generated(java.lang.String string, javax.swing.Icon icon, boolean boolean0)
	{
		super( string,icon,boolean0);
	}
	 
	public  LogScale_generated(java.lang.String string, javax.swing.Icon icon)
	{
		super( string,icon);
	}
	 
	public  LogScale_generated(java.lang.String string)
	{
		super( string);
	}
	 
	public  LogScale_generated(javax.swing.Action action)
	{
		super( action);
	}
	 
	public  LogScale_generated(javax.swing.Icon icon, boolean boolean0)
	{
		super( icon,boolean0);
	}
	 
	public  LogScale_generated(javax.swing.Icon icon)
	{
		super( icon);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_LogScaleEvent()
	{
		(new star.hydrology.ui.chart.horton.LogScaleEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}