/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.ui.chart.horton;

public class LogScaleEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  LogScaleEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  LogScaleEvent(star.hydrology.ui.chart.horton.LogScaleEvent event)
	{
		super( event ) ;
	}
	 
	public  LogScaleEvent(star.hydrology.ui.chart.horton.LogScaleRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}