/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydro.tribs;

public abstract class TRibsForm_generated extends javax.swing.JPanel implements star.event.EventController, star.event.Listener, star.hydrology.events.tribs.AnimationRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  TRibsForm_generated()
	{
		super();
	}
	 
	public  TRibsForm_generated(boolean boolean0)
	{
		super( boolean0);
	}
	 
	public  TRibsForm_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super( layoutManager,boolean0);
	}
	 
	public  TRibsForm_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydrology.events.UnprojectedMapChangedEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.UnprojectedMapChangedEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			handleNewMap( (star.hydrology.events.UnprojectedMapChangedRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".handleNewMap "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void handleNewMap(star.hydrology.events.UnprojectedMapChangedRaiser r);
	 
	public void raise_AnimationEvent()
	{
		(new star.hydrology.events.tribs.AnimationEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydrology.events.UnprojectedMapChangedEvent.class);
	}
	 
}