/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.tribs;

public class AnimationEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  AnimationEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  AnimationEvent(star.hydrology.events.tribs.AnimationEvent event)
	{
		super( event ) ;
	}
	 
	public  AnimationEvent(star.hydrology.events.tribs.AnimationRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}