/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class AdjustableValueEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  AdjustableValueEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  AdjustableValueEvent(star.hydrology.events.AdjustableValueEvent event)
	{
		super( event ) ;
	}
	 
	public  AdjustableValueEvent(star.hydrology.events.AdjustableValueRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}