/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class CurvaturePDFEvent extends star.hydrology.events.PDFEvent
{
	private static final long serialVersionUID = 1L;

	public  CurvaturePDFEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  CurvaturePDFEvent(star.hydrology.events.CurvaturePDFEvent event)
	{
		super( event ) ;
	}
	 
	public  CurvaturePDFEvent(star.hydrology.events.CurvaturePDFRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}