/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class DrainageDensityAndStreamFrequencyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  DrainageDensityAndStreamFrequencyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  DrainageDensityAndStreamFrequencyEvent(star.hydrology.events.DrainageDensityAndStreamFrequencyEvent event)
	{
		super( event ) ;
	}
	 
	public  DrainageDensityAndStreamFrequencyEvent(star.hydrology.events.DrainageDensityAndStreamFrequencyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}