/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class ElevationPDFEvent extends star.hydrology.events.PDFEvent
{
	private static final long serialVersionUID = 1L;

	public  ElevationPDFEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ElevationPDFEvent(star.hydrology.events.ElevationPDFEvent event)
	{
		super( event ) ;
	}
	 
	public  ElevationPDFEvent(star.hydrology.events.ElevationPDFRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}