/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class GridStatisticsProviderChangeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  GridStatisticsProviderChangeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  GridStatisticsProviderChangeEvent(star.hydrology.events.GridStatisticsProviderChangeEvent event)
	{
		super( event ) ;
	}
	 
	public  GridStatisticsProviderChangeEvent(star.hydrology.events.GridStatisticsProviderChangeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}