/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class InitializeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  InitializeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  InitializeEvent(star.hydrology.events.InitializeEvent event)
	{
		super( event ) ;
	}
	 
	public  InitializeEvent(star.hydrology.events.InitializeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}