/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class IUHEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  IUHEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  IUHEvent(star.hydrology.events.IUHEvent event)
	{
		super( event ) ;
	}
	 
	public  IUHEvent(star.hydrology.events.IUHRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}