/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class LayerChangedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  LayerChangedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  LayerChangedEvent(star.hydrology.events.LayerChangedEvent event)
	{
		super( event ) ;
	}
	 
	public  LayerChangedEvent(star.hydrology.events.LayerChangedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}