/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class LinkConcentrationEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  LinkConcentrationEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  LinkConcentrationEvent(star.hydrology.events.LinkConcentrationEvent event)
	{
		super( event ) ;
	}
	 
	public  LinkConcentrationEvent(star.hydrology.events.LinkConcentrationRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}