/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class MainStreamLengthEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  MainStreamLengthEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  MainStreamLengthEvent(star.hydrology.events.MainStreamLengthEvent event)
	{
		super( event ) ;
	}
	 
	public  MainStreamLengthEvent(star.hydrology.events.MainStreamLengthRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}