/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class PDFEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  PDFEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  PDFEvent(star.hydrology.events.PDFEvent event)
	{
		super( event ) ;
	}
	 
	public  PDFEvent(star.hydrology.events.PDFRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}