/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class Pick3DEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  Pick3DEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  Pick3DEvent(star.hydrology.events.Pick3DEvent event)
	{
		super( event ) ;
	}
	 
	public  Pick3DEvent(star.hydrology.events.Pick3DRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}