/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class ProjectionChangedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProjectionChangedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ProjectionChangedEvent(star.hydrology.events.ProjectionChangedEvent event)
	{
		super( event ) ;
	}
	 
	public  ProjectionChangedEvent(star.hydrology.events.ProjectionChangedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}