/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class RainfallGaugesEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  RainfallGaugesEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  RainfallGaugesEvent(star.hydrology.events.RainfallGaugesEvent event)
	{
		super( event ) ;
	}
	 
	public  RainfallGaugesEvent(star.hydrology.events.RainfallGaugesRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}