/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class RainfallGaugesTimeseriesEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  RainfallGaugesTimeseriesEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  RainfallGaugesTimeseriesEvent(star.hydrology.events.RainfallGaugesTimeseriesEvent event)
	{
		super( event ) ;
	}
	 
	public  RainfallGaugesTimeseriesEvent(star.hydrology.events.RainfallGaugesTimeseriesRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}