/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class SelectWatershedOriginEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  SelectWatershedOriginEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  SelectWatershedOriginEvent(star.hydrology.events.SelectWatershedOriginEvent event)
	{
		super( event ) ;
	}
	 
	public  SelectWatershedOriginEvent(star.hydrology.events.SelectWatershedOriginRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}