/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class Select3DWatershedOriginEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  Select3DWatershedOriginEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  Select3DWatershedOriginEvent(star.hydrology.events.Select3DWatershedOriginEvent event)
	{
		super( event ) ;
	}
	 
	public  Select3DWatershedOriginEvent(star.hydrology.events.Select3DWatershedOriginRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}