/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class SimpleIUHAdjustPanelEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  SimpleIUHAdjustPanelEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  SimpleIUHAdjustPanelEvent(star.hydrology.events.SimpleIUHAdjustPanelEvent event)
	{
		super( event ) ;
	}
	 
	public  SimpleIUHAdjustPanelEvent(star.hydrology.events.SimpleIUHAdjustPanelRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}