/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class SlopeAreaEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  SlopeAreaEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  SlopeAreaEvent(star.hydrology.events.SlopeAreaEvent event)
	{
		super( event ) ;
	}
	 
	public  SlopeAreaEvent(star.hydrology.events.SlopeAreaRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}