/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class StreamOrderStatisticsEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  StreamOrderStatisticsEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  StreamOrderStatisticsEvent(star.hydrology.events.StreamOrderStatisticsEvent event)
	{
		super( event ) ;
	}
	 
	public  StreamOrderStatisticsEvent(star.hydrology.events.StreamOrderStatisticsRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}