/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class TopIndexPDFEvent extends star.hydrology.events.PDFEvent
{
	private static final long serialVersionUID = 1L;

	public  TopIndexPDFEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  TopIndexPDFEvent(star.hydrology.events.TopIndexPDFEvent event)
	{
		super( event ) ;
	}
	 
	public  TopIndexPDFEvent(star.hydrology.events.TopIndexPDFRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}