/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class UnprojectedMapChangedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  UnprojectedMapChangedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  UnprojectedMapChangedEvent(star.hydrology.events.UnprojectedMapChangedEvent event)
	{
		super( event ) ;
	}
	 
	public  UnprojectedMapChangedEvent(star.hydrology.events.UnprojectedMapChangedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}