/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class VisibilityChangedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  VisibilityChangedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  VisibilityChangedEvent(star.hydrology.events.VisibilityChangedEvent event)
	{
		super( event ) ;
	}
	 
	public  VisibilityChangedEvent(star.hydrology.events.VisibilityChangedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}