/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events;

public class WidthFunctionEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WidthFunctionEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  WidthFunctionEvent(star.hydrology.events.WidthFunctionEvent event)
	{
		super( event ) ;
	}
	 
	public  WidthFunctionEvent(star.hydrology.events.WidthFunctionRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}