/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.worker.pdf.reg;

public abstract class CurvatureRaiser_generated extends java.lang.Object implements star.event.EventController, star.hydrology.events.regionalization.RegCurvaturePDFRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  CurvatureRaiser_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_RegCurvaturePDFEvent()
	{
		(new star.hydrology.events.regionalization.RegCurvaturePDFEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
	}
	 
}