/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.worker.pdf.reg;

public abstract class RegionalizationExporter_generated extends java.lang.Object implements star.event.EventController, star.event.GatedListener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  RegionalizationExporter_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		getAdapter().addGatedAnd( new Class[]{ star.hydrology.events.map.RegionalizeWorkerMapLayerEvent.class,star.hydrology.events.map.FilledMapLayerEvent.class},new Class[]{},true);
	}
	 
	abstract void discretisizeLayer(star.hydrology.events.map.RegionalizeWorkerMapLayerRaiser r, star.hydrology.events.map.FilledMapLayerRaiser mr);
	 
	private void eventAndGateRaisedHandles(final star.event.Event in_event[], final boolean valid)
	{
		final star.event.Event[] event = in_event;
		if( event != null && valid && event.length == 2 && event[0].getClass().getName().equals( "star.hydrology.events.map.RegionalizeWorkerMapLayerEvent" ) && event[1].getClass().getName().equals( "star.hydrology.events.map.FilledMapLayerEvent" ) &&  true )
		{
			
			utils.Runner.runOnThread(new Runnable() { 
				public void run() { 
					long start = System.nanoTime();
					discretisizeLayer( (star.hydrology.events.map.RegionalizeWorkerMapLayerRaiser)event[0].getSource(),(star.hydrology.events.map.FilledMapLayerRaiser)event[1].getSource() );
					long end = System.nanoTime();
				if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".discretisizeLayer "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public void eventsRaised(final star.event.Event event[], final boolean valid)
	{
		eventAndGateRaisedHandles(event,valid);
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void removeNotify()
	{
		getAdapter().removeGatedAnd( new Class[]{ star.hydrology.events.map.RegionalizeWorkerMapLayerEvent.class,star.hydrology.events.map.FilledMapLayerEvent.class},new Class[]{});
	}
	 
}