/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.ui;

public abstract class HortonNumbers_generated extends javax.swing.JPanel implements star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  HortonNumbers_generated()
	{
		super();
	}
	 
	public  HortonNumbers_generated(boolean boolean0)
	{
		super( boolean0);
	}
	 
	public  HortonNumbers_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super( layoutManager,boolean0);
	}
	 
	public  HortonNumbers_generated(java.awt.LayoutManager layoutManager)
	{
		super( layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addContained(star.hydrology.ui.chart.horton.LogScaleEvent.class );
		getAdapter().addContained(star.hydrology.ui.chart.horton.TrendLineEvent.class );
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeContained(star.hydrology.ui.chart.horton.LogScaleEvent.class );
		getAdapter().removeContained(star.hydrology.ui.chart.horton.TrendLineEvent.class );
	}
	 
}