/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package app.ui;

public abstract class HortonNumberLabel_generated extends javax.swing.JLabel implements star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  HortonNumberLabel_generated()
	{
		super();
	}
	 
	public  HortonNumberLabel_generated(java.lang.String string, int int0)
	{
		super( string,int0);
	}
	 
	public  HortonNumberLabel_generated(java.lang.String string, javax.swing.Icon icon, int int0)
	{
		super( string,icon,int0);
	}
	 
	public  HortonNumberLabel_generated(java.lang.String string)
	{
		super( string);
	}
	 
	public  HortonNumberLabel_generated(javax.swing.Icon icon, int int0)
	{
		super( icon,int0);
	}
	 
	public  HortonNumberLabel_generated(javax.swing.Icon icon)
	{
		super( icon);
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.hydrology.events.HortonNumberEvent.class);
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.hydrology.events.HortonNumberEvent" ) && event.isValid() ) 
		{
			 utils.Runner.runOnThread(new Runnable() { public void run() { 
			 long start = System.nanoTime();
			update( (star.hydrology.events.HortonNumberRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".update "  + ( end-start )/1000000 ); } }},this,2);
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.hydrology.events.HortonNumberEvent.class);
	}
	 
	abstract void update(star.hydrology.events.HortonNumberRaiser r);
	 
}