/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.regionalization;

public class RegElevationPDFEvent extends star.hydrology.events.PDFEvent
{
	private static final long serialVersionUID = 1L;

	public  RegElevationPDFEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  RegElevationPDFEvent(star.hydrology.events.regionalization.RegElevationPDFEvent event)
	{
		super( event ) ;
	}
	 
	public  RegElevationPDFEvent(star.hydrology.events.regionalization.RegElevationPDFRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}