/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.regionalization;

public class RegSlopePDFEvent extends star.hydrology.events.PDFEvent
{
	private static final long serialVersionUID = 1L;

	public  RegSlopePDFEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  RegSlopePDFEvent(star.hydrology.events.regionalization.RegSlopePDFEvent event)
	{
		super( event ) ;
	}
	 
	public  RegSlopePDFEvent(star.hydrology.events.regionalization.RegSlopePDFRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}