/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.regionalization;

public class RegTopindexPDFEvent extends star.hydrology.events.PDFEvent
{
	private static final long serialVersionUID = 1L;

	public  RegTopindexPDFEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  RegTopindexPDFEvent(star.hydrology.events.regionalization.RegTopindexPDFEvent event)
	{
		super( event ) ;
	}
	 
	public  RegTopindexPDFEvent(star.hydrology.events.regionalization.RegTopindexPDFRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}