/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.events;

public class AccumulationThresholdChangedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  AccumulationThresholdChangedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  AccumulationThresholdChangedEvent(starhydro.events.AccumulationThresholdChangedEvent event)
	{
		super( event ) ;
	}
	 
	public  AccumulationThresholdChangedEvent(starhydro.events.AccumulationThresholdChangedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}