/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.events;

public class BackgroundProcessEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  BackgroundProcessEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  BackgroundProcessEvent(starhydro.events.BackgroundProcessEvent event)
	{
		super( event ) ;
	}
	 
	public  BackgroundProcessEvent(starhydro.events.BackgroundProcessRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}