/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.events;

public class DelineateWatershedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  DelineateWatershedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  DelineateWatershedEvent(starhydro.events.DelineateWatershedEvent event)
	{
		super( event ) ;
	}
	 
	public  DelineateWatershedEvent(starhydro.events.DelineateWatershedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}