/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.events;

public class LoadTileEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  LoadTileEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  LoadTileEvent(starhydro.events.LoadTileEvent event)
	{
		super( event ) ;
	}
	 
	public  LoadTileEvent(starhydro.events.LoadTileRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}