/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.events;

public class OpenInStarHydroEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  OpenInStarHydroEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  OpenInStarHydroEvent(starhydro.events.OpenInStarHydroEvent event)
	{
		super( event ) ;
	}
	 
	public  OpenInStarHydroEvent(starhydro.events.OpenInStarHydroRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}