/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.events;

public class ViewScaleChangedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ViewScaleChangedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ViewScaleChangedEvent(starhydro.events.ViewScaleChangedEvent event)
	{
		super( event ) ;
	}
	 
	public  ViewScaleChangedEvent(starhydro.events.ViewScaleChangedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}