/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.events;

public class ViewLocationChangeEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ViewLocationChangeEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ViewLocationChangeEvent(starhydro.events.ViewLocationChangeEvent event)
	{
		super( event ) ;
	}
	 
	public  ViewLocationChangeEvent(starhydro.events.ViewLocationChangeRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}