/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package starhydro.events;

public class WatershedAvailableEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  WatershedAvailableEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  WatershedAvailableEvent(starhydro.events.WatershedAvailableEvent event)
	{
		super( event ) ;
	}
	 
	public  WatershedAvailableEvent(starhydro.events.WatershedAvailableRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}