/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class CurvaturePDFLMapLayerEvent extends star.hydrology.events.map.MapLayerEvent
{
	private static final long serialVersionUID = 1L;

	public  CurvaturePDFLMapLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  CurvaturePDFLMapLayerEvent(star.hydrology.events.map.CurvaturePDFLMapLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  CurvaturePDFLMapLayerEvent(star.hydrology.events.map.CurvaturePDFLMapLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}