/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class ElevationPDFMapLayerEvent extends star.hydrology.events.map.MapLayerEvent
{
	private static final long serialVersionUID = 1L;

	public  ElevationPDFMapLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ElevationPDFMapLayerEvent(star.hydrology.events.map.ElevationPDFMapLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  ElevationPDFMapLayerEvent(star.hydrology.events.map.ElevationPDFMapLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}