/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class FlowaccumulationMapLayerEvent extends star.hydrology.events.map.MapLayerEvent
{
	private static final long serialVersionUID = 1L;

	public  FlowaccumulationMapLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  FlowaccumulationMapLayerEvent(star.hydrology.events.map.FlowaccumulationMapLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  FlowaccumulationMapLayerEvent(star.hydrology.events.map.FlowaccumulationMapLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}