/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class MapLayerEvent extends star.hydrology.events.LayerChangedEvent
{
	private static final long serialVersionUID = 1L;

	public  MapLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  MapLayerEvent(star.hydrology.events.map.MapLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  MapLayerEvent(star.hydrology.events.map.MapLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}