/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class RegionalizationStatisticsEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  RegionalizationStatisticsEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  RegionalizationStatisticsEvent(star.hydrology.events.map.RegionalizationStatisticsEvent event)
	{
		super( event ) ;
	}
	 
	public  RegionalizationStatisticsEvent(star.hydrology.events.map.RegionalizationStatisticsRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}