/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class RegionalizationEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  RegionalizationEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  RegionalizationEvent(star.hydrology.events.map.RegionalizationEvent event)
	{
		super( event ) ;
	}
	 
	public  RegionalizationEvent(star.hydrology.events.map.RegionalizationRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}