/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class SimpleIUHMapLayerEvent extends star.hydrology.events.map.MapLayerEvent
{
	private static final long serialVersionUID = 1L;

	public  SimpleIUHMapLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  SimpleIUHMapLayerEvent(star.hydrology.events.map.SimpleIUHMapLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  SimpleIUHMapLayerEvent(star.hydrology.events.map.SimpleIUHMapLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}