/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class SlopePDFMapLayerEvent extends star.hydrology.events.map.MapLayerEvent
{
	private static final long serialVersionUID = 1L;

	public  SlopePDFMapLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  SlopePDFMapLayerEvent(star.hydrology.events.map.SlopePDFMapLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  SlopePDFMapLayerEvent(star.hydrology.events.map.SlopePDFMapLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}