/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class TerrainMapLayerEvent extends star.hydrology.events.map.MapLayerEvent
{
	private static final long serialVersionUID = 1L;

	public  TerrainMapLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  TerrainMapLayerEvent(star.hydrology.events.map.TerrainMapLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  TerrainMapLayerEvent(star.hydrology.events.map.TerrainMapLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}