/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class TopindexPDFMapLayerEvent extends star.hydrology.events.map.MapLayerEvent
{
	private static final long serialVersionUID = 1L;

	public  TopindexPDFMapLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  TopindexPDFMapLayerEvent(star.hydrology.events.map.TopindexPDFMapLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  TopindexPDFMapLayerEvent(star.hydrology.events.map.TopindexPDFMapLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}