/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.hydrology.events.map;

public class WatershedLayerEvent extends star.hydrology.events.map.MapLayerEvent
{
	private static final long serialVersionUID = 1L;

	public  WatershedLayerEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  WatershedLayerEvent(star.hydrology.events.map.WatershedLayerEvent event)
	{
		super( event ) ;
	}
	 
	public  WatershedLayerEvent(star.hydrology.events.map.WatershedLayerRaiser raiser)
	{
		super( raiser ) ;
	}
	 
	public void raise()
	{
		raiseImpl();
	}
	 
}